apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-webapp
spec: 
  selector:
    matchLabels:
      app: kube-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-webapp
    spec:
      containers:
        - name: nginx
          image: kube-webapp
          imagePullPolicy: Never
          ports:
            - containerPort: 80

